<?php

namespace Database\Seeders;

use App\Models\Estacao;
use Illuminate\Database\Seeder;

class EstacaoSeeder extends Seeder
{
    public function run(): void
    {
        $estacoes = [
            [
                'site_id' => '4G-ABLAJ1',
                'tipo_elemento' => 'ENODE B',
                'tecnologia' => 'LTE',
                'tipo_conexao' => 'Indefinido',
                'endereco_id' => 'ACABL_0001',
                'classificacao' => 'RANSHARING',
                'data_aquisicao' => '2021-09-29',
                'detentor_area' => 'IHS BRAZIL',
                'tipo_contrato_infra' => 'Built-to-Suit',
                'detentor_infra' => 'IHS BRAZIL',
                'tipo_infra' => 'Greenfield',
                'observacao' => 'CANDIDATO A',
                'tipo_logradouro' => 'RUA',
                'logradouro' => 'MANOEL BATISTA DE ARAÚJO',
                'numero' => 'S/N',
                'complemento' => 'QUADRA 12, LOTE 09',
                'bairro' => 'CENTRO',
                'municipio' => 'ASSIS BRASIL',
                'estado' => 'AC',
                'cep' => '69935000',
                'regional' => 'TCO',
                'latitude' => -10.925094,
                'longitude' => -69.554056,
                'status' => 'Aquisitado',
                'aev_nominal' => 0,
                'area_solo' => 0,
                'altura_estrutura' => 40,
                'station_id' => '68010010',
                'ots' => 'Não',
            ],
            [
                'site_id' => 'AC10J1',
                'tipo_elemento' => 'NODE B',
                'tecnologia' => 'UMTS',
                'tipo_conexao' => 'Interconexão',
                'endereco_id' => 'ACACLD0001',
                'classificacao' => 'ACESSO',
                'data_aquisicao' => '2004-02-10',
                'detentor_area' => 'AMERICAN TOWER',
                'tipo_contrato_infra' => 'Compartilhado',
                'detentor_infra' => 'AMERICAN TOWER',
                'tipo_infra' => 'Greenfield',
                'tipo_ev' => 'TORRE METALICA TRIANGULAR',
                'fornecedor_ev' => 'BRASILSAT',
                'tipo_logradouro' => 'AVENIDA',
                'logradouro' => 'PARANA',
                'numero' => '122',
                'complemento' => 'OU PRINCIPAL, QUADRA 03',
                'bairro' => 'CENTRO',
                'municipio' => 'ACRELANDIA',
                'estado' => 'AC',
                'cep' => '69945000',
                'regional' => 'TCO',
                'latitude' => -10.075556,
                'longitude' => -67.055611,
                'status' => 'Aquisitado',
                'altura_estrutura' => 60,
                'station_id' => 'ACR001TM',
                'observacao_thq' => 'VENDIDO GENESIS - 2º CLOSING',
                'ots' => 'Não',
            ],
            [
                'site_id' => 'AC1001',
                'tipo_elemento' => 'NODE B',
                'tecnologia' => 'UMTS',
                'tipo_conexao' => 'Interconexão',
                'endereco_id' => 'ACACLD0001',
                'classificacao' => 'ACESSO',
                'data_aquisicao' => '2004-02-10',
                'detentor_area' => 'AMERICAN TOWER',
                'tipo_contrato_infra' => 'Compartilhado',
                'detentor_infra' => 'AMERICAN TOWER',
                'tipo_infra' => 'Greenfield',
                'tipo_ev' => 'TORRE METALICA TRIANGULAR',
                'fornecedor_ev' => 'BRASILSAT',
                'tipo_logradouro' => 'AVENIDA',
                'logradouro' => 'PARANA',
                'numero' => '122',
                'complemento' => 'OU PRINCIPAL, QUADRA 03',
                'bairro' => 'CENTRO',
                'municipio' => 'ACRELANDIA',
                'estado' => 'AC',
                'cep' => '69945000',
                'regional' => 'TCO',
                'latitude' => -10.075556,
                'longitude' => -67.055611,
                'status' => 'Aquisitado',
                'altura_estrutura' => 60,
                'station_id' => 'ACR001TM',
                'observacao_thq' => 'VENDIDO GENESIS - 2º CLOSING',
                'ots' => 'Não',
            ],
            [
                'site_id' => 'ACLD01',
                'tipo_elemento' => 'BTS',
                'tecnologia' => 'GSM',
                'tipo_conexao' => 'Interconexão',
                'endereco_id' => 'ACACLD0001',
                'classificacao' => 'ACESSO',
                'data_aquisicao' => '2004-02-10',
                'detentor_area' => 'AMERICAN TOWER',
                'tipo_contrato_infra' => 'Compartilhado',
                'detentor_infra' => 'AMERICAN TOWER',
                'tipo_infra' => 'Greenfield',
                'tipo_ev' => 'TORRE METALICA TRIANGULAR',
                'fornecedor_ev' => 'BRASILSAT',
                'tipo_logradouro' => 'AVENIDA',
                'logradouro' => 'PARANA',
                'numero' => '122',
                'complemento' => 'OU PRINCIPAL, QUADRA 03',
                'bairro' => 'CENTRO',
                'municipio' => 'ACRELANDIA',
                'estado' => 'AC',
                'cep' => '69945000',
                'regional' => 'TCO',
                'latitude' => -10.075556,
                'longitude' => -67.055611,
                'status' => 'Aquisitado',
                'altura_estrutura' => 60,
                'station_id' => 'ACR001TM',
                'observacao_thq' => 'VENDIDO GENESIS - 2º CLOSING',
                'ots' => 'Não',
            ],
            [
                'site_id' => 'AZ1001',
                'tipo_elemento' => 'NODE B',
                'tecnologia' => 'UMTS',
                'endereco_id' => 'ACACLD0001',
                'classificacao' => 'ACESSO',
                'data_aquisicao' => '2004-02-10',
                'detentor_area' => 'AMERICAN TOWER',
                'tipo_contrato_infra' => 'Compartilhado',
                'detentor_infra' => 'AMERICAN TOWER',
                'tipo_infra' => 'Greenfield',
                'tipo_ev' => 'TORRE METALICA TRIANGULAR',
                'fornecedor_ev' => 'BRASILSAT',
                'tipo_logradouro' => 'AVENIDA',
                'logradouro' => 'PARANA',
                'numero' => '122',
                'complemento' => 'OU PRINCIPAL, QUADRA 03',
                'bairro' => 'CENTRO',
                'municipio' => 'ACRELANDIA',
                'estado' => 'AC',
                'cep' => '69945000',
                'regional' => 'TCO',
                'latitude' => -10.075556,
                'longitude' => -67.055611,
                'status' => 'Aquisitado',
                'altura_estrutura' => 60,
                'station_id' => 'ACR001TM',
                'observacao_thq' => 'VENDIDO GENESIS - 2º CLOSING',
                'ots' => 'Não',
            ],
            [
                'site_id' => 'DZ0303',
                'tipo_elemento' => 'NODE B',
                'tecnologia' => 'UMTS',
                'endereco_id' => 'ACACLD0001',
                'classificacao' => 'ACESSO',
                'data_aquisicao' => '2004-02-10',
                'detentor_area' => 'AMERICAN TOWER',
                'tipo_contrato_infra' => 'Compartilhado',
                'detentor_infra' => 'AMERICAN TOWER',
                'tipo_infra' => 'Greenfield',
                'tipo_ev' => 'TORRE METALICA TRIANGULAR',
                'fornecedor_ev' => 'BRASILSAT',
                'tipo_logradouro' => 'AVENIDA',
                'logradouro' => 'PARANA',
                'numero' => '122',
                'complemento' => 'OU PRINCIPAL, QUADRA 03',
                'bairro' => 'CENTRO',
                'municipio' => 'ACRELANDIA',
                'estado' => 'AC',
                'cep' => '69945000',
                'regional' => 'TCO',
                'latitude' => -10.075556,
                'longitude' => -67.055611,
                'status' => 'Aquisitado',
                'altura_estrutura' => 60,
                'station_id' => 'ACR001TM',
                'observacao_thq' => 'VENDIDO GENESIS - 2º CLOSING',
                'situacao' => 'Site Removido',
                'ots' => 'Não',
            ],
        ];

        foreach ($estacoes as $dados) {
            Estacao::updateOrCreate(
                ['site_id' => $dados['site_id']],
                $dados,
            );
        }
    }
}
